name: EVM Forge Tests

on:
  push:
    branches: [feature/*, bugfix/*, task/*]
  pull_request:
    branches: [main, develop]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: Install Forge
        run: npm add --global @foundry-rs/forge@1.5

      - name: Run Forge build
        run: forge build

      - name: Run Forge tests
        run: forge test --ffi --gas-report